name: KFCPvP
author: messageofdeath
version: 1.0
depend: [messageofdeathLib, MaterialAPI]
softdepend: [Votifier]
main: me.messageofdeath.KFCPvP.KFCPvP
commands:
  infchest:
  kfcpvp:
  stats:
  vote:
